name: Report PR stats

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  report-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for base coverage report
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-base
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Wait for head coverage report
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-head
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: cd ci && yarn

      - name: Send PR comment with coverage diff
        run: |
          node ci/sendPRStatsComment.js ${{ secrets.GITHUB_TOKEN }} ${{ github.event.number }} ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
