name: Report PR stats

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  report-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for head coverage report
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-head
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Wait for base coverage report
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-base
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.base.sha }}

      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: cd ci && yarn

      - name: Download coverage reports
        run: |
          node ci/getCoverageReports.js ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}

      - name: Extract downloaded reports
        run: |
          cd ci

          mkdir base-coverage
          mkdir head-coverage

          unzip base-coverage.zip -d base-coverage
          tar -xzvf base-coverage/coverage.tgz -C base-coverage

          unzip head-coverage.zip -d head-coverage
          tar -xzvf head-coverage/coverage.tgz -C head-coverage


          ls -la base-coverage

      - name: Send PR comment with coverage diff
        run: |
          cd ci
          node sendCoveragePRComment.js base-coverage/coverage-summary.json head-coverage/coverage-summary.json ${{ github.event.number }} ${{ secrets.GITHUB_TOKEN }}
